version: '3'
services:
  web:
    build: .
    volumes: ['.:/code']
    ports:
     - "80:5000"
     - "443:5000"
    networks:
    my-network:
        aliases:
            - web
  redis:
    image: "redis:alpine"
    
networks:
    web
   